Feature/#9 feat exercise main
NOW-SOPT-APP3-PlanFit/PlanFit-Android pull request #13
Opened 2024-05-15 16:54 UTC by seohee0925

## 📌 PR 요약
근력 운동 뷰 구현

🌱 작업한 내용
- gif 부분은 Glide 이용
- recycler view item ui 구현

🌱 PR 포인트
- 근력 운동 뷰 구현
- 텍스트 안 보이는 부분은 서버에서 받아오는 부분이라 `tools`로 처리
- 세트 수정 관련해서 `MultiAdapter` 사용하는게 맞을까요?!

## 📸 스크린샷
https://github.com/NOW-SOPT-APP3-PlanFit/PlanFit-Android/assets/102652293/31a6b42c-ffd3-4e41-a568-d88d5d15d5de

## 📮 관련 이슈
- Resolved: #9

2024-05-16 07:06 UTC, Sangwook123 requested changes
너무 잘하시는데요? ㄷㄷ 컨벤션도 잘맞춰주셨네요 굿입니다 ! 변경사항 조금 있으니까 확인 부탁드릴게요 ~!

2024-05-16 07:06 UTC, Sangwook123 commented on app/src/main/res/layout/activity_exercise_main.xml
> +                    android:layout_width="312dp"
이부분 고정dp 쓰기보단 0dp랑 마진, constraint ratio 활용해 볼 수 있을 것 같습니다

2024-05-16 07:06 UTC, Sangwook123 commented on app/build.gradle.kts
> +    implementation("com.github.bumptech.glide:glide:4.12.0")
제가 말씀을 못드렸는데 이미지 로딩 라이브러리 coil로 통일하려고 합니다 ! coil로 변경 가능할까요? toml파일에 추가되어있어서 libs.coil 이런식으로 의존성 추가하시면 될거에요 !

2024-05-16 07:06 UTC, Sangwook123 commented on app/src/main/java/org/sopt/app3/planfit/core/ui/activity/ExerciseMainActivity.kt
> +        Glide.with(this)
coil도 gif 지원하는걸로 알고있습니다 ! 변경 부탁드릴게요~~!

2024-05-16 07:06 UTC, Sangwook123 commented on app/src/main/res/layout/activity_exercise_main.xml
> +                <androidx.recyclerview.widget.RecyclerView
nestedscrollview 안에서 아이템 개수가 많은 recyclerview를 사용했을 때 발생할 수 있는 문제점은 무엇일까요?

2024-05-16 14:28 UTC, hyoeunjoo reviewed
깔끔하다... 이름도 다 잘지었다... 최고다!!!

2024-05-16 15:47 UTC, seohee0925 commented on app/src/main/res/layout/activity_exercise_main.xml
> +                    android:layout_width="312dp"
아하 그렇게 할 수 있군요 수정할게요!

2024-05-16 15:49 UTC, seohee0925 commented on app/build.gradle.kts
> +    implementation("com.github.bumptech.glide:glide:4.12.0")
`coil`로 변경하겠습니다! 감사합니다

2024-05-16 16:00 UTC, seohee0925 commented on app/src/main/res/layout/activity_exercise_main.xml
> +                <androidx.recyclerview.widget.RecyclerView
`NestedScrollView` 안에 `RecyclerView`를 사용할 경우 `RecyclerView`는 아이템을 전부 미리 생성하게 돼서 뷰를 재사용하는 장점이 사라집니다....... 그래서 아이템이 많은 경우에는 `NestedScrollView`를 지양하고 `RecyclerView`에서 여러 개의 `ViewHolder`를 사용할 수 있도록 `Viewholder`를 관리해주면 된다고 합니다! 세트 상태에 따라서 `ViewHolder` 여러개 만들어서 해보겠습니당

2024-05-16 16:46 UTC, Sangwook123 commented on app/src/main/res/layout/activity_exercise_main.xml
> +                <androidx.recyclerview.widget.RecyclerView
음.. 지금같은 경우에는 recycler view 아이템 개수가 한정적이어서 지금처럼 해도 될것같아요 ! 만약 아이템 개수가 너무 많은 경우(몇십개 이상)에만 해당되는 내용입니다 ! 운동을 몇백세트 하는거 아니면 지금은 괜찮을 것 같아유

2024-05-16 16:58 UTC, seohee0925 commented on app/src/main/res/layout/activity_exercise_main.xml
> +                <androidx.recyclerview.widget.RecyclerView
아하!!!!!!!! 그러면 저 궁금한게 있는데 상태에 따라 MultiAdapter를 쓸건데 그럼 Adapter만 여러개 만들고 ViewHolder 한개로 진행하는게 맞을까요?!

2024-05-16 17:05 UTC, Sangwook123 commented on app/src/main/res/layout/activity_exercise_main.xml
> +                <androidx.recyclerview.widget.RecyclerView
음 리사이클러뷰에서 MultiViewType을 사용한다는 것은 여러 종류의 레이아웃을 한 리사이클러뷰 안에서 표현하고자 할때 의미가 있는 것 같습니다. 세트 완료시 색상이 달라지는 부분을 표현하는 것을 말씀하시는 것 같은데 색상이 달라졌을때 색상이 다른 별도의 아이템레이아웃을 사용한다면, MultiViewType Adapter와 2개의 뷰홀더를, 단순 레이아웃 내 색상 변경으로 표현하고자 한다면, 하나의 어댑터와 하나의 뷰홀더로도 충분할 것 같습니다.

2024-05-16 17:14 UTC, seohee0925 commented on app/src/main/res/layout/activity_exercise_main.xml
> +                <androidx.recyclerview.widget.RecyclerView
아하 이해했습니다! 별도의 아이템 레이아웃을 따로 만들어놔서 상태에 따라 뷰홀더를 사용해보도록 하겠습니다! 감사합니다...🙇‍♀️🙇‍♀️

2024-05-17 06:38 UTC, Sangwook123 approved these changes
LGTM~!

2024-05-17 07:31 UTC, merged