[Feat] #14 근력운동뷰 구현
NOW-SOPT-APP3-PlanFit/PlanFit-Android pull request #18
Opened 2024-05-17 17:25 UTC by seohee0925

## 📌 PR 요약
- 세트 추가 누를 경우 세트 추가
- 세트 상태(`Completed`, `InProgress`, `Remaining`) 에 따라 리사이클러뷰 상태 변경

🌱 작업한 내용
- 

🌱 PR 포인트
-

## 📸 스크린샷

https://github.com/NOW-SOPT-APP3-PlanFit/PlanFit-Android/assets/102652293/8b07c3e0-e3a5-41ef-b354-df4701e9c188

## 📮 관련 이슈
- Resolved: #14 

## 기타 ✨ 
RecyclerView 순서
1️⃣  item layout 만들기
2️⃣  viewHolder에서 item과 연결시킬 bind 함수 작성 (생성자로 바인딩, onBind에는 데이터 연결)
3️⃣  adapter에서 viewHolder를 create시키고, bind시키기
4️⃣  activity나 fragment에서 adapter 생성

2024-05-18 04:14 UTC, Sangwook123 requested changes
미쳤다 너무 잘한다.. 변경 요청사항 리뷰 남김니다

2024-05-18 04:14 UTC, Sangwook123 commented on app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainActivity.kt
> +    private var setCnt = 1
얘넨 viewmodel에서 관리해줘도 좋을듯 !

2024-05-18 04:14 UTC, Sangwook123 commented on app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainActivity.kt
> +        val ivHeart: ImageView = binding.ivExerciseMainHeart
불필요한 변수 선언 같아요 ~!

2024-05-18 04:14 UTC, Sangwook123 commented on app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/SetViewModel.kt
> +    var mockSetList: MutableList<SetCount> = mutableListOf(
val로 ..!

2024-05-18 04:14 UTC, Sangwook123 commented on app/src/main/java/org/sopt/app3/planfit/domain/model/SetCount.kt
> +    abstract val id: Int
이렇게 되면 abstract val을 setCnt로 변경하고 id는 없애도 괜찮을 것 같아요 ! 그리고 어댑터의 diffutil에서는 id가 아닌 setCnt로 비교하면 될 것 같습니다.

2024-05-18 06:27 UTC, seohee0925 commented on app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/SetViewModel.kt
> +    var mockSetList: MutableList<SetCount> = mutableListOf(
헉스.... 땡큐

2024-05-18 06:28 UTC, seohee0925 commented on app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainActivity.kt
> +        val ivHeart: ImageView = binding.ivExerciseMainHeart
아하 with로 binding 묶어서 처리하겠습니담

2024-05-19 14:30 UTC, seohee0925 commented on app/src/main/java/org/sopt/app3/planfit/domain/model/SetCount.kt
> +    abstract val id: Int
아하 그렇네요! `setCnt`만 사용하도록 하겠습니다

2024-05-19 14:44 UTC, seohee0925 commented on app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainActivity.kt
> +    private var setCnt = 1
아하 오케!!!!

2024-05-20 12:34 UTC, Sangwook123 approved these changes
LGTM!

2024-05-21 00:53 UTC, merged